/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./templates/**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#4cd7f6",
        "background": "#131314",
        "primary": "#ddb7ff",
        "surface-container-low": "#1c1b1c",
        "primary-fixed-dim": "#ddb7ff",
        "on-surface-variant": "#cfc2d6",
        "on-primary-container": "#400071",
        "outline-variant": "#4d4354",
        "inverse-primary": "#842bd2",
        "tertiary-container": "#009eb9",
        "on-error": "#690005",
        "inverse-surface": "#e5e2e3",
        "primary-container": "#b76dff",
        "on-primary-fixed": "#2c0051",
        "surface-container-lowest": "#0e0e0f",
        "error": "#ffb4ab",
        "secondary-container": "#aa0266",
        "on-primary": "#490080",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#001f26",
        "surface-dim": "#131314",
        "outline": "#988d9f",
        "secondary-fixed": "#ffd9e4",
        "on-tertiary": "#003640",
        "on-background": "#e5e2e3",
        "surface-variant": "#353436",
        "on-secondary-fixed-variant": "#8c0053",
        "tertiary-fixed": "#acedff",
        "surface-container-highest": "#353436",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#3e0022",
        "inverse-on-surface": "#313031",
        "surface-tint": "#ddb7ff",
        "secondary-fixed-dim": "#ffb0cd",
        "surface-bright": "#3a393a",
        "on-secondary-container": "#ffbad3",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-primary-fixed-variant": "#6900b3",
        "tertiary": "#4cd7f6",
        "secondary": "#ffb0cd",
        "primary-fixed": "#f0dbff",
        "on-secondary": "#640039",
        "surface-container-high": "#2a2a2b",
        "on-tertiary-container": "#002f38",
        "surface-container": "#201f20",
        "on-surface": "#e5e2e3",
        "surface": "#131314"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "md": "16px",
        "lg": "24px",
        "gutter": "24px",
        "sm": "8px",
        "xxl": "80px",
        "xl": "48px",
        "margin": "32px",
        "xs": "4px",
        "container-max": "1440px"
      },
      fontFamily: {
        "body-lg": ["Inter", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        "h3": ["Inter", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        "body-md": ["Inter", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        "stat-value": ["Inter", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        "label-sm": ["Inter", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        "h2": ["Inter", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        "h1": ["Inter", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "h3": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "stat-value": ["20px", {"lineHeight": "1", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "h2": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "h1": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
