name: License Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.3'

      - name: Install addlicense
        run: go install github.com/google/addlicense@latest

      - name: Check License Headers
        run: |
          addlicense -check -l mit -c "arumes31" **/*.go
